Screen: 
    name: 'Page3'
    CameraPreview:
        id:camerapreview
        camera:camera
        orientation: 'vertical'
        size: root.size
        Image:
            id: camera
            size: root.size
        ImageButton:
            source: 'data/cameraicon.png'
            size: 75, 75
            center: root.width * 0.5, root.height * 0.1
            on_press:camerapreview.play()
        

